# Address of flight controller
# Use "ls /dev/serial/by-id" to list serial devices
fc_port: /dev/serial/by-id/usb-FTDI_TTL232R-3V3_FTCKTT1F-if00-port0
fc_baud: 57600

# Ground Control Station over Meshnet (NordVPN)
# Utilise soit le hostname Meshnet (recommandé), soit l'IP Meshnet
# Exemple : alexismg.lallement-everest.nord:14550
gcs_remote: alexismg.lallement-everest.nord:14550

# MAVLink stream to AMMcamera
streamer_ipport: 127.0.0.1:14551

# Messages to send, with rate in Hz. 0 is disabled, -1 is allow all 
skylink_messages:
 AHRS: 0
 AHRS2: 0
 AOA_SSA: 0
 ATTITUDE: 0.5
 AUTOPILOT_VERSION: 0
 BATTERY_STATUS: 0.2
 BATTERY2: 0.2
 COMMAND_ACK: -1
 DISTANCE_SENSOR: 0
 EKF_STATUS_REPORT: 0.2
 GLOBAL_POSITION_INT: 0.5
 GPS_GLOBAL_ORIGIN: 0
 GPS_RAW_INT: 0
 GPS2_RAW: 0
 HEARTBEAT: 0.5
 HOME_POSITION: 0
 HWSTATUS: 0
 LOCAL_POSITION_NED: 0
 MEMINFO: 0
 MISSION_CURRENT: 0
 NAMED_VALUE_FLOAT: 0
 PARAM_VALUE: 0
 POWER_STATUS: 0
 RANGEFINDER: 0
 RAW_IMU: 0
 RC_CHANNELS: 0
 SCALED_IMU2: 0
 SCALED_IMU3: 0
 SCALED_PRESSURE: 0
 SCALED_PRESSURE2: 0
 SERVO_OUTPUT_RAW: 0
 STATUSTEXT: 0
 SYS_STATUS: -1
 SYSTEM_TIME: 0
 TERRAIN_REPORT: 0
 TIMESYNC: 0
 VFR_HUD: 0.5
 VIBRATION: 0
 WIND: 0

